### ISSUE TITLE
Request: include rendered docs in the git repo

### ISSUE THREAD

**Issue by billdueber** [mlibrary/checkpoint#6]
...so everyone -- say me -- who wants to read the docs prettily doesn't have to install the Sphinx toolchain. Unless that's what you're going for, is to make us all install that... Devious. 

For reals, might be easy with a githook.

**Comment by botimer** [comment]
Oh, hey @billdueber... Didn't see this earlier. Does RTD suit your needs?

https://checkpoint.readthedocs.io/en/latest/

**Comment by billdueber** [comment]
Yeah, sorry, the readthedocs site is great. Thanks!

**Comment by botimer** [comment]
Nice. Now to just make the docs useful! 😄
